version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/advanced_mern_social_project/backend
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root    
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE    